//
// Created by arman on 07/05/2026.
//

#ifndef C_INVENTORY_DYNAMIC_TAB_SYSTEM_INVENTORY_SYSTEM_H
#define C_INVENTORY_DYNAMIC_TAB_SYSTEM_INVENTORY_SYSTEM_H

void initiateInventory();

#endif //C_INVENTORY_DYNAMIC_TAB_SYSTEM_INVENTORY_SYSTEM_H
